### ISSUE TITLE
Alma - Nilde

### ISSUE THREAD

**Issue by MonicaBerzacola** [bediniupi/nilde-openurl#1]
Titolo del capitolo: se inserisco il titolo nel campo "Numero capitolo" non viene trasmesso in Nilde; se inserisco il titolo nel campo "Titolo capitolo" viene trasmesso correttamente. Se inserisco il titolo in entrambi i campi, viene trasmesso duplicato.
Altra nota: va a finire nel form articoli, non parti di libro e quindi non può prendere l'ISBN

**Comment by bediniupi** [comment]
Sì, mi pare il comportamento corretto, i campi dovrebbero essere utilizzati così:
Titolo del capitolo = "Introduzione"
Numero Capitolo "1"
Il risultato è "1 Introduzione"

Per quanto riguarda la scelta del form questo è un comportamento di Nilde, che sceglie parti di libro solo se l'ISBN viene valorizzato, non conosco altri modi di selezionare il modulo via openurl, quindi in Alma per avere il campo ISBN e valorizzarlo occorre usare book request e non article request.

**Comment by MonicaBerzacola** [comment]
Capito. Nel form online degli utenti utilizziamo il campo Numero capitolo al posto di Titolo capitolo perché nelle richieste ILLSBN viene trasmesso solo il campo Numero capitolo. Ok, basta spostare il titolo nel campo corretto. 
Per quanto riguarda la richiesta di capitoli e form nilde, abbiamo utilizzato il book request in Alma, ma il volume non ha ISBN (capita frequentemente). Se inserisco un dato fittizio nel campo ISBN mi seleziona il form giusto in Nilde?

**Comment by bediniupi** [comment]
Per ora sì (basta un ?), comunque dalla [documentazione di Nilde](https://nildeworld.bo.cnr.it/en/kb/integration-databases-nilde) pare che si possa scegliere il modulo anche a seconda di questi parametri:

Genre definition:
rft_val_fmt:    info:ofi/fmt:kev:mtx:journal  (for articles only)
rft_val_fmt:    info:ofi/fmt:kev:mtx:book  (for books only)

A questo punto potrei utilizzarli a seconda del modulo scelto in Alma (book o article) senza la stretta necessità di inserire l'ISBN: faccio dei test e casomai aggiorno anche le istruzioni:

Aspetterò lunedì per pubblicare la nuova release nel caso ci siano altri problemi da risolvere.

**Comment by MonicaBerzacola** [comment]
Form parti di libro: inserendo in Alma "?" non funziona, ho provato anche con "ISBN", ma rimane il form articoli. Bisogna inserire un dato numerico, es "1234"
Per ora usiamo questo escamotage
Grazie di tutto!!!!

**Comment by bediniupi** [comment]
ok,  evidentemente esiste un controllo sull'ISBN, effettuerò la modifica basata sul tipo di richiesta in Alma.

**Comment by MonicaBerzacola** [comment]
Ti segnalo un problema. I nostri utenti inoltrano le richieste da Primo e il form online è piuttosto stringato. Il campo "Chapter" va a finire nel campo "Chapter number" di Alma, non nel "Chapter title". Non ci sono altri campi che vanno a valorizzare il Chapter title. Sai come si può risolvere?
Così come funziona l'app, bisogna fare il taglia/incolla ogni volta del titolo del capitolo... un po' scomodo.

**Comment by bediniupi** [comment]
Ai fini dell'invio a Nilde è lo stesso, si dovrebbe presentare questo caso:
Titolo capitolo = "" [vuoto]
Numero capitolo = "titolo del capitolo"
in nilde la stringa è costruita numero capitolo + [spazio] + titolo capitolo, quindi alla fine a Nilde arriva "titolo del capitolo" lo stesso.

**Comment by MonicaBerzacola** [comment]
Hai ragione. Non so perché, ma nella prima prova che avevo fatto non passava il titolo inserito nel campo Numero capitolo. Avrò sbagliato qualcosa...
Grazie!

**Comment by bediniupi** [comment]
Ho pubblicato la release 1.2, modificando anche la pagina di aiuto per renderla più completa, inoltre ora non è più necessario complilare per forza il campo ISBN per le richieste di capitoli di libri, viene scelto automaticamente se in Alma viene usato il modulo di richiesta libri.
Ora chiudo questa issue come risolta, se hai altro da segnalare apri pure un'altra issue.

**Comment by MonicaBerzacola** [comment]
GRAZIE!!!
